/**
 * @author Martín Vladimir Alonso Sierra Galvis
 * @maintainer Martín Vladimir Alonso Sierra Galvis
 * @version 1.0.0
 */

/** Actividades */
export const REMOVE_ACTIVITY = 'REMOVE_ACTIVITY';
export const SET_ACTIVITIES = 'SET_ACTIVITIES';
export const SET_ACTIVITY = 'SET_ACTIVITY';
export const SET_SELECTED_SESSION = 'SET_SELECTED_SESSION';
export const SET_SESSIONS = 'SET_SESSIONS';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';

/** Auth */
export const SET_PATIENT_REFRESH_TOKEN = 'SET_PATIENT_REFRESH_TOKEN';
export const SET_PATIENT_TOKEN = 'SET_PATIENT_TOKEN';
export const SET_THERAPIST_REFRESH_TOKEN = 'SET_THERAPIST_REFRESH_TOKEN';
export const SET_THERAPIST_TOKEN = 'SET_THERAPIST_TOKEN';

/** Avatar */
export const SET_AVATAR_MESSAGE = 'SET_AVATAR_MESSAGE';
export const SET_AVATAR_VARIATIONS = 'SET_AVATAR_VARIATIONS';

/** Configuración */
export const RESET_CONFIGURATION = 'RESET_CONFIGURATION';
export const SET_CONFIGURATION = 'SET_CONFIGURATION';

/** Configuración dinámica */
export const RESET_DYNAMIC_OPTIONS = 'RESET_DYNAMIC_OPTIONS';
export const SET_DYNAMIC_OPTIONS = 'SET_DYNAMIC_OPTIONS';
export const SET_DYNAMIC_SELECTED_OPTIONS = 'SET_DYNAMIC_SELECTED_OPTIONS';

/** Configuración estática */
export const ADD_STATIC_SELECTED_OPTION = 'ADD_STATIC_SELECTED_OPTION';
export const RESET_STATIC_OPTIONS = 'RESET_STATIC_OPTIONS';
export const SET_STATIC_OPTIONS = 'SET_STATIC_OPTIONS';
export const SET_STATIC_SELECTED_OPTIONS = 'SET_STATIC_SELECTED_OPTIONS';

/** Colecciones */
export const SET_COLLECTIONS = 'SET_COLLECTIONS';
export const SET_COLLECTABLE = 'SET_COLLECTABLE';
export const SET_USER_SKINS_OWNED = 'SET_USER_SKINS_OWNED';
export const SET_USER_SKIN_OWNED = 'SET_USER_SKIN_OWNED';

/** Conexión */
export const SET_CHECK_SERVER_STATUS = 'SET_CHECK_SERVER_STATUS';
export const SET_CONNECTED_ID = 'SET_CONNECTED_ID';
export const SET_CONNECT_SOCKET = 'SET_CONNECT_SOCKET';

/** Feedback */
export const SET_FEEDBACK_DATA = 'SET_FEEDBACK_DATA';
export const SET_FEEDBACK_DATE = 'SET_FEEDBACK_DATE';

/** Pacientes */
export const REMOVE_PATIENT = 'REMOVE_PATIENT';
export const SET_PATIENT = 'SET_PATIENT';
export const SET_PATIENTS = 'SET_PATIENTS';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';

/** UI */
export const SET_BAR = 'SET_BAR';
export const SET_FULLSCREEN = 'SET_FULLSCREEN';
export const SET_MODAL = 'SET_MODAL';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_PARALLAX = 'SET_PARALLAX';
export const SET_V_OFFSET = 'SET_V_OFFSET';
export const SET_WINDOW_WIDTH = 'SET_WINDOW_WIDTH';
export const SHOW_AVATAR = 'SHOW_AVATAR';
export const SHOW_CREATE_ACTIVITY_BUTTON = 'SHOW_CREATE_ACTIVITY_BUTTON';
export const SHOW_MOBILE_MENU = 'SHOW_MOBILE_MENU';

/** User */
export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const SET_TO_UPDATE = 'SET_TO_UPDATE';